### Import DATA

In [2]:
import pandas as pd 
import plotly.express as px
import matplotlib.pyplot as plt 
import seaborn as sns   
import numpy as np

In [3]:
PATH = '/Users/Marcy_Student/Desktop/Capstone/nyc-dog-licensing_expanded/data/Cleaned /final_dataset.csv'
df = pd.read_csv(PATH)

- Quick overview of the data

In [4]:
df.head(30)

,Name,Gender,BirthYear,Breed,ZipCode,IssuedDate,ExpiredDate,ExtractYear,Borough,DogAgeAtLicense,IssueYear,IssueMonth
0,PAIGE,F,2014.0,American Pit Bull Mix / Pit Bull Mix,10035.0,2014-09-12,2017-09-12,2016,Manhattan,0.0,2014,September
1,YOGI,M,2010.0,Boxer,10465.0,2014-09-12,2017-10-02,2016,The Bronx,4.0,2014,September
2,ALI,M,2014.0,Basenji,10013.0,2014-09-12,2019-09-12,2016,Manhattan,0.0,2014,September
3,QUEEN,F,2013.0,Akita Crossbreed,10013.0,2014-09-12,2017-09-12,2016,Manhattan,1.0,2014,September
4,LOLA,F,2009.0,Maltese,10028.0,2014-09-12,2017-10-09,2016,Manhattan,5.0,2014,September
5,IAN,M,2006.0,Unknown,10013.0,2014-09-12,2019-10-30,2016,Manhattan,8.0,2014,September
6,BUDDY,M,2008.0,Unknown,10025.0,2014-09-12,2017-10-20,2016,Manhattan,6.0,2014,September
7,CHEWBACCA,F,2012.0,Labrador Retriever Crossbreed,10013.0,2014-09-12,2019-10-01,2016,Manhattan,2.0,2014,September
8,HEIDI-BO,F,2007.0,Dachshund Smooth Coat,11215.0,2014-09-13,2017-04-16,2016,Brooklyn,7.0,2014,September
9,MASSIMO,M,2009.0,"Bull Dog, French",11201.0,2014-09-13,2017-09-17,2016,Brooklyn,5.0,2014,September
10,LOLA,F,2006.0,Miniature Pinscher,10022.0,2014-09-13,2019-10-03,2016,Manhattan,8.0,2014,September
11,LEMMY,F,2005.0,Yorkshire Terrier,10003.0,2014-09-13,2017-10-26,2016,Manhattan,9.0,2014,September
12,LUCY,F,2014.0,Dachshund Smooth Coat Miniature,11215.0,2014-09-13,2019-09-13,2016,Brooklyn,0.0,2014,September
13,RICKY,M,2014.0,German Shepherd Dog,11220.0,2014-09-13,2017-09-13,2016,Brooklyn,0.0,2014,September
14,SARAH,F,2012.0,Unknown,10040.0,2014-09-13,2017-09-13,2016,Manhattan,2.0,2014,September
15,MURPHY,M,2012.0,American Pit Bull Mix / Pit Bull Mix,10463.0,2014-09-13,2017-09-28,2016,The Bronx,2.0,2014,September
16,JUNE,F,2010.0,Cavalier King Charles Spaniel,11238.0,2014-09-13,2019-10-28,2016,Brooklyn,4.0,2014,September
17,ELIZABETH,F,2013.0,Cavalier King Charles Spaniel,10022.0,2014-09-13,2019-09-13,2016,Manhattan,1.0,2014,September
18,AVERY,F,2014.0,American Pit Bull Terrier/Pit Bull,10002.0,2014-09-13,2019-09-13,2016,Manhattan,0.0,2014,September
19,SOPHIE,F,2011.0,Boxer,10308.0,2014-09-13,2019-10-23,2016,Staten Island,3.0,2014,September
20,OTIS,F,2001.0,Unknown,10011.0,2014-09-13,2017-09-29,2016,Manhattan,13.0,2014,September
21,BENSON,M,2010.0,Boxer,11209.0,2014-09-13,2019-10-29,2016,Brooklyn,4.0,2014,September
22,BIGS,M,2004.0,American Pit Bull Terrier/Pit Bull,11208.0,2014-09-13,2019-10-27,2016,Brooklyn,10.0,2014,September
23,LOGAN,M,2003.0,Unknown,10011.0,2014-09-13,2017-10-30,2016,Manhattan,11.0,2014,September
24,BESS,F,2010.0,Beagle,11218.0,2014-09-13,2016-09-13,2016,Brooklyn,4.0,2014,September
25,APPLE,M,2013.0,Havanese,10025.0,2014-09-13,2019-10-16,2016,Manhattan,1.0,2014,September
26,MUNECA,F,2013.0,Beagle,11232.0,2014-09-13,2019-09-13,2016,Brooklyn,1.0,2014,September
27,DOTTIE,F,2013.0,"Poodle, Standard",10025.0,2014-09-13,2017-09-13,2016,Manhattan,1.0,2014,September
28,OSCAR,M,2008.0,German Shorthaired Pointer,10025.0,2014-09-13,2019-09-13,2016,Manhattan,6.0,2014,September
29,BUDDY,M,2012.0,Bull Terrier,10312.0,2014-09-13,2019-10-05,2016,Staten Island,2.0,2014,September

- Let's check the data type for each column in the dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720803 entries, 0 to 720802
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Name             720803 non-null  object
 1   Gender           720803 non-null  object
 2   BirthYear        720803 non-null  float64
 3   Breed            720803 non-null  object
 4   ZipCode          720803 non-null  float64
 5   IssuedDate       720803 non-null  object
 6   ExpiredDate      720803 non-null  object
 7   ExtractYear      720803 non-null  int64
 8   Borough          720803 non-null  object
 9   DogAgeAtLicense  720803 non-null  float64
 10  IssueYear        720803 non-null  int64
 11  IssueMonth       720803 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 66.0+ MB

Let's change the data type for the dates columns

- Let's check for missing values inside the dataset

In [6]:
df.isna().sum()

Name               0
Gender             0
BirthYear          0
Breed              0
ZipCode            0
IssuedDate         0
ExpiredDate        0
ExtractYear        0
Borough            0
DogAgeAtLicense    0
IssueYear          0
IssueMonth         0
dtype: int64

- It look like there are not many values missing in this dataset
- Let's drop all the missing values.

In [7]:
df.dropna(inplace=True)

In [8]:
df.isna().sum()

Name               0
Gender             0
BirthYear          0
Breed              0
ZipCode            0
IssuedDate         0
ExpiredDate        0
ExtractYear        0
Borough            0
DogAgeAtLicense    0
IssueYear          0
IssueMonth         0
dtype: int64

In [9]:
df.columns

Index(['Name', 'Gender', 'BirthYear', 'Breed', 'ZipCode', 'IssuedDate',
       'ExpiredDate', 'ExtractYear', 'Borough', 'DogAgeAtLicense', 'IssueYear',
       'IssueMonth'],
      dtype='object')

- Let's rename the columns for easy data handling

In [10]:
df = df.rename(columns={
    "AnimalName":"Name",
    "AnimalGender":"Gender",
    "AnimalBirthYear":"BirthYear",
    "BreedName":"Breed",
    "LicenseIssuedDate":"IssuedDate",
    "LicenseExpiredDate":"ExpiredDate",
    "Extract Year":"ExtractYear",
})

In [11]:
df.head()

,Name,Gender,BirthYear,Breed,ZipCode,IssuedDate,ExpiredDate,ExtractYear,Borough,DogAgeAtLicense,IssueYear,IssueMonth
0,PAIGE,F,2014.0,American Pit Bull Mix / Pit Bull Mix,10035.0,2014-09-12,2017-09-12,2016,Manhattan,0.0,2014,September
1,YOGI,M,2010.0,Boxer,10465.0,2014-09-12,2017-10-02,2016,The Bronx,4.0,2014,September
2,ALI,M,2014.0,Basenji,10013.0,2014-09-12,2019-09-12,2016,Manhattan,0.0,2014,September
3,QUEEN,F,2013.0,Akita Crossbreed,10013.0,2014-09-12,2017-09-12,2016,Manhattan,1.0,2014,September
4,LOLA,F,2009.0,Maltese,10028.0,2014-09-12,2017-10-09,2016,Manhattan,5.0,2014,September

- Let's change the data type for certain columns in the right format to help us find insight wiht the data
- Also this can help us for example use date time function on the dates columns to extract the month or the year.

In [12]:
# Convert dates to datetime
df["IssuedDate"] = pd.to_datetime(df["IssuedDate"],errors='coerce')
df["ExpiredDate"] = pd.to_datetime(df["ExpiredDate"],errors='coerce')
# Convert BirthYear to numeric
df['BirthYear'] = pd.to_numeric(df['BirthYear'], errors='coerce')

Let's create a dictionary to map zip codes with borough names
- Using borough we are going to explore areas with lower licensing compliance, which can help in targeted public health and safety campaigns.

In [13]:
zipcodes = {
    'Manhattan': (10001, 10282),
    'The Bronx': (10451, 10475),
    'Brooklyn': (11201, 11256),
    'Queens': [(11004, 11109), (11351, 11697)],
    'Staten Island': (10301, 10314)
}
def get_borough(zipcode):
    if pd.isna(zipcode):
        return 'Unknown'
    if zipcodes['Manhattan'][0] <= zipcode <= zipcodes['Manhattan'][1]:
        return 'Manhattan'
    elif zipcodes['The Bronx'][0] <= zipcode <= zipcodes['The Bronx'][1]:
        return 'The Bronx'
    elif zipcodes['Brooklyn'][0] <= zipcode <= zipcodes['Brooklyn'][1]:
        return 'Brooklyn'
    elif (zipcodes['Queens'][0][0] <= zipcode <= zipcodes['Queens'][0][1]) or \
         (zipcodes['Queens'][1][0] <= zipcode <= zipcodes['Queens'][1][1]):
        return 'Queens'
    elif zipcodes['Staten Island'][0] <= zipcode <= zipcodes['Staten Island'][1]:
        return 'Staten Island'
    else:
        return 'Unknown'
df['Borough'] = df['ZipCode'].apply(get_borough)

In [14]:
df['Borough'].head()

0    Manhattan
1    The Bronx
2    Manhattan
3    Manhattan
4    Manhattan
Name: Borough, dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720803 entries, 0 to 720802
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Name             720803 non-null  object
 1   Gender           720803 non-null  object
 2   BirthYear        720803 non-null  float64
 3   Breed            720803 non-null  object
 4   ZipCode          720803 non-null  float64
 5   IssuedDate       720803 non-null  datetime64[ns]
 6   ExpiredDate      720803 non-null  datetime64[ns]
 7   ExtractYear      720803 non-null  int64
 8   Borough          720803 non-null  object
 9   DogAgeAtLicense  720803 non-null  float64
 10  IssueYear        720803 non-null  int64
 11  IssueMonth       720803 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(2), object(5)
memory usage: 66.0+ MB

The following line of code create a new columns to store the Dog age when the licence is made
- This column can help us later to group the data by borough and get the average dog age.

In [16]:
df['IssueYear'] = df['IssuedDate'].dt.year
df['IssueMonth'] = df['IssuedDate'].dt.month_name()
df['DogAgeAtLicense'] = df['IssueYear'] - df['BirthYear']

#The following line of code create a new columns to store the Dog age when the licence is made
#This column can help us later to group the data by borough and get the average dog age.

In [17]:
df.head(10)

,Name,Gender,BirthYear,Breed,ZipCode,IssuedDate,ExpiredDate,ExtractYear,Borough,DogAgeAtLicense,IssueYear,IssueMonth
0,PAIGE,F,2014.0,American Pit Bull Mix / Pit Bull Mix,10035.0,2014-09-12,2017-09-12,2016,Manhattan,0.0,2014,September
1,YOGI,M,2010.0,Boxer,10465.0,2014-09-12,2017-10-02,2016,The Bronx,4.0,2014,September
2,ALI,M,2014.0,Basenji,10013.0,2014-09-12,2019-09-12,2016,Manhattan,0.0,2014,September
3,QUEEN,F,2013.0,Akita Crossbreed,10013.0,2014-09-12,2017-09-12,2016,Manhattan,1.0,2014,September
4,LOLA,F,2009.0,Maltese,10028.0,2014-09-12,2017-10-09,2016,Manhattan,5.0,2014,September
5,IAN,M,2006.0,Unknown,10013.0,2014-09-12,2019-10-30,2016,Manhattan,8.0,2014,September
6,BUDDY,M,2008.0,Unknown,10025.0,2014-09-12,2017-10-20,2016,Manhattan,6.0,2014,September
7,CHEWBACCA,F,2012.0,Labrador Retriever Crossbreed,10013.0,2014-09-12,2019-10-01,2016,Manhattan,2.0,2014,September
8,HEIDI-BO,F,2007.0,Dachshund Smooth Coat,11215.0,2014-09-13,2017-04-16,2016,Brooklyn,7.0,2014,September
9,MASSIMO,M,2009.0,"Bull Dog, French",11201.0,2014-09-13,2017-09-17,2016,Brooklyn,5.0,2014,September

- Let's count the number of `licences` by `Borough`
- We can use Group

In [18]:
licenses_by_borough=df.groupby('Borough')['IssuedDate'].count().reset_index(False)

In [19]:
licenses_by_borough

         Borough  IssuedDate
0       Brooklyn      194153
1      Manhattan      241353
2         Queens      148539
3  Staten Island       59735
4      The Bronx       74519
5        Unknown        2504

In [20]:
df.groupby("IssueMonth")["IssuedDate"].count().sort_values(ascending=False)

IssueMonth
July         69123
August       67560
September    64871
March        62607
January      60489
June         60228
October      60156
May          58981
April        57378
February     56455
December     52946
November     50009
Name: IssuedDate, dtype: int64

Look like the licences are most made in summer!
- July it the peek month
- November is the month with the lowest licences made.

Let's create a quick visual with plotly to see the difference in number of licences for each Borough

In [21]:
fig = px.bar(licenses_by_borough, x="Borough",y="IssuedDate", title="Dog licences by borough")
fig.show()
#It look like Manhattan the borought wiht the highest Dog licences

Now let's fiter out unrealistic dogs ages. 
In this large dataset, we can get bad data, like:
Dogs that appear to be 30 years old, which is not realistic (the average dog lifespan is 10–15 years)
So let's remove rows where:
- The age is less than 0 → probably a mistake
- The age is more than 25 → extremely rare or likely wrong

In [22]:
df_cleaned = df[(df['DogAgeAtLicense'] >= 0) & (df['DogAgeAtLicense'] <= 25)]

In [23]:
averageage = df.groupby("Borough")["DogAgeAtLicense"].mean()

In [24]:
averageage

Borough
Brooklyn         4.610611
Manhattan        5.124519
Queens           5.163533
Staten Island    5.882079
The Bronx        4.641447
Unknown          3.969649
Name: DogAgeAtLicense, dtype: float64

Now Let's export the cleaned dataset

In [25]:
df_cleaned.to_csv("final_dataset.csv", index=False)